[package]
name = "dope-quic"
version = "0.12.0"
edition = "2024"
description = "QUIC x dope"
license = "MIT"
repository = "https://github.com/dope-rs/quic"
readme = "README.md"

[dependencies]
o3 = "=0.16.3"
shin = "0.17"
dope = "0.15"
ring = "0.17"
subtle = "2.6"
pin-project = "1"

[dev-dependencies]
dope-gen = "0.15"

[[bench]]
name = "conn_first_flush"
harness = false

[[test]]
name = "client_reconnect"
path = "tests/client_reconnect/main.rs"

[[test]]
name = "loopback_handshake"
path = "tests/loopback_handshake/main.rs"

[[test]]
name = "retained_receive"
path = "tests/retained_receive/main.rs"
